[package]
name = "lyrebird"
description = "this package uses youtube-dl and is a discord bot. How could this be bad?"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.23.0", features = ["full"] }
tracing-subscriber = "0.3.16"
lazy_static = "1.4.0"
tracing = "0.1.37"
reqwest = { version = "0.11.14", default-features = false, features = ["rustls-tls"] }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.songbird]
git = "https://github.com/serenity-rs/songbird.git"
branch = "next"
features = [ "builtin-queue" ]

[dependencies.serenity]
git = "https://github.com/serenity-rs/serenity"
branch = "next"
default-features = false
features = ["client", "model", "cache", "voice", "rustls_backend"]

[dependencies.symphonia]
features = ["aac", "mp3", "isomp4", "alac"]
